{% set name = "pcl" %}
{% set build_number = 3 %}
{% set version = "1.12.0" %}
{% set major_version = version.split(".")[0] %}
{% set minor_version = version.split(".")[1] %}
{% set sha256 = "21dfa9a268de9675c1f94d54d9402e4e02120a0aa4215d064436c52b7d5bd48f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pointcloudlibrary/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  run_exports:
    - {{ pin_subpackage('pcl', max_pin='x.x.x') }}
  string: {{ build_variant }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build_number }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - {{ cdt('mesa-dri-drivers') }}   # [linux]
    - {{ cdt('libselinux') }}         # [linux]
    - {{ cdt('libxdamage') }}         # [linux]
    - {{ cdt('libxxf86vm') }}         # [linux]
    - {{ cdt('libxext') }}            # [linux]
    - {{ cdt('mesa-libegl-devel') }}  # [build_variant == "egl"]
    - cmake
    - ninja                           # [win]
    - make                            # [unix]
  host:
    - xorg-libxfixes                  # [linux]
    - flann
    - eigen
    - boost-cpp
    - qhull
    - vtk * {{ build_variant }}*
    - glew  # [build_variant == "qt"]
  run:
    - flann
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - qhull
    - vtk * {{ build_variant }}*
    - glew  # [build_variant == "qt"]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -d $PREFIX/include/{{ name }}-{{ major_version }}.{{ minor_version }}/{{ name }}              # [not win] 
    - if not exist %LIBRARY_INC%\\{{ name }}-{{ major_version }}.{{ minor_version }}\\{{ name }} exit 1  # [win] 

about:
  home: http://www.pointclouds.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Cloud Library (PCL)
  description: |
    The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.
  doc_url: http://www.pointclouds.org
  dev_url: https://github.com/pointcloudlibrary/pcl

extra:
  recipe-maintainers:
    - chambbj
    - hobu
    - Tobias-Fischer
